"""empty message

Revision ID: d89ec1be7672
Revises: 45306f6c7762
Create Date: 2024-01-06 22:57:26.893956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89ec1be7672'
down_revision = '45306f6c7762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_url_junction',
    sa.Column('workflows_id', sa.Integer(), nullable=True),
    sa.Column('workflow_urls_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_urls_id'], ['workflow_urls.id'], ),
    sa.ForeignKeyConstraint(['workflows_id'], ['workflows.id'], )
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('website_urls')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_urls', sa.VARCHAR(length=500), nullable=False))

    op.drop_table('workflow_url_junction')
    op.drop_table('workflow_urls')
    # ### end Alembic commands ###
